CREATE TABLE TaiKhoan (
    MaTaiKhoan NVARCHAR(20) PRIMARY KEY,
    TenTaiKhoan NVARCHAR(50) NOT NULL,
    MatKhau NVARCHAR(50) NOT NULL,
    HoVaTen NVARCHAR(200) NOT NULL,
    CCCD VARCHAR(12) NOT NULL,
    CapBac NVARCHAR(50) NOT NULL,
    QuanHam NVARCHAR(50) NOT NULL,
    ChucVu NVARCHAR(50) NOT NULL,
    DonVi NVARCHAR(100) NOT NULL,
    NgayThangNamSinh DATE NOT NULL,
    GioiTinh NVARCHAR(5),
    ChieuCao NVARCHAR(10)
);

CREATE TABLE ThiSinh (
    MaThiSinh NVARCHAR(20) PRIMARY KEY,
    HoVaTen NVARCHAR(200) NOT NULL,
    CCCD NVARCHAR(20) NOT NULL,
    CapBac NVARCHAR(50) NOT NULL,
    QuanHam NVARCHAR(50) NOT NULL,
    ChucVu NVARCHAR(50) NOT NULL,
    DonVi NVARCHAR(100) NOT NULL,
    NgayThangNamSinh DATE NOT NULL,
    GioiTinh NVARCHAR(5),
    ChieuCao NVARCHAR(10)
);

CREATE TABLE Loi (
    MaLoi NVARCHAR(20) PRIMARY KEY,
    TenLoi NVARCHAR(200) NOT NULL,
    TrongSo INT NOT NULL,
    GhiChu NVARCHAR(MAX)
);

CREATE TABLE BaiThi (
    MaBaiThi NVARCHAR(20) PRIMARY KEY,
    TenBaiThi NVARCHAR(200) NOT NULL,
    DiemGoc INT NOT NULL,
    MaGiamKhao NVARCHAR(20) NOT NULL,
    ThoiGianThi DATE NOT NULL,
    DiaDiemThi NVARCHAR(50) NOT NULL,
    DiemTru INT NOT NULL,
    KetQua INT NOT NULL,
    FOREIGN KEY (MaGiamKhao) REFERENCES TaiKhoan(MaTaiKhoan)
);

CREATE TABLE ChiTietLoiCuaThiSinh (
    MaChiTiet NVARCHAR(20) PRIMARY KEY,
    MaThiSinh NVARCHAR(20) NOT NULL,
    MaLoi NVARCHAR(20) NOT NULL,
    ThoiDiemLoi DATETIME NOT NULL,
    MaBaiThi NVARCHAR(20) NOT NULL,
    FOREIGN KEY (MaThiSinh) REFERENCES ThiSinh(MaThiSinh),
    FOREIGN KEY (MaLoi) REFERENCES Loi(MaLoi),
    FOREIGN KEY (MaBaiThi) REFERENCES BaiThi(MaBaiThi)
);
